#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal._3_Persistencia.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="gringlobal")]
	public partial class ModeloBuscarDuplicadosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ModeloBuscarDuplicadosDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GrinGlobalConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloBuscarDuplicadosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloBuscarDuplicadosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloBuscarDuplicadosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloBuscarDuplicadosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarDuplicados")]
		public ISingleResult<BuscarDuplicadosResult> BuscarDuplicados([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((ISingleResult<BuscarDuplicadosResult>)(result.ReturnValue));
		}
	}
	
	public partial class BuscarDuplicadosResult
	{
		
		private string _plant_name;
		
		private System.Nullable<int> _percent_viable;
		
		private System.DateTime _tested_date;
		
		public BuscarDuplicadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plant_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string plant_name
		{
			get
			{
				return this._plant_name;
			}
			set
			{
				if ((this._plant_name != value))
				{
					this._plant_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_percent_viable", DbType="Int")]
		public System.Nullable<int> percent_viable
		{
			get
			{
				return this._percent_viable;
			}
			set
			{
				if ((this._percent_viable != value))
				{
					this._percent_viable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tested_date", DbType="DateTime2 NOT NULL")]
		public System.DateTime tested_date
		{
			get
			{
				return this._tested_date;
			}
			set
			{
				if ((this._tested_date != value))
				{
					this._tested_date = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
